remote_theme: "BDHU/minimalist@f19d6a6ef015ba93c5aee9ce80339e4959b0ffa7"

logo: /images/pfp.png
favicon: true

description: A simple little site to host my rating distribution and some of my writing on music.

sidebar:
  - name: Album of the Year
    icon: <img src="/images/aoty.png" width="16" height="16">
    link: https://www.albumoftheyear.org/user/ashfromupthere/
  - name: Rate Your Music
    icon: <img src="/images/rym.png" width="16" height="16">
    link: https://www.rateyourmusic.com/~ashlynn
  - name: Discord
    icon: <img src="/images/discord.png" width="16" height="16">
    link: https://discord.com/users/672828366159740954
